
# Target specific macrs
TARGET = nxtLEGO_client
TARGET_SOURCES := \
	client_requests.c \
	client_lego.c 
TOPPERS_OSEK_OIL_SOURCE := ./conf.oil

O_PATH ?= build

include ../../../nxtOSEK/ecrobot/ecrobot.mak
